# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 RAEN Digital Tools SL - PyNET Platform

# Button: import the turbine-clearance results for the active zone into Civil 3D.
# Source: 04_QGIS/output/<slug>/desbroce_aerogeneradores.json
#         (generated by 07_DesbroceAerogeneradores.py).
# Draws one clearance circle per turbine on layer GIS_DESBROCE_AG, DRAPED on the first
# TIN surface, coloured by the combined priority score (vegetation x generation):
# red >=60, orange >=35, green otherwise. A label (priority, id, %fuel, AEP) sits next
# to each. Re-running cleans the layer first.

import clr
import json
from pathlib import Path

clr.AddReference("AcMgd")
clr.AddReference("AcCoreMgd")
clr.AddReference("AcDbMgd")
clr.AddReference("AecBaseMgd")
clr.AddReference("AeccDbMgd")

from Autodesk.AutoCAD.ApplicationServices import Application as AcadApp
from Autodesk.AutoCAD.DatabaseServices import (
    OpenMode, BlockTableRecord, LayerTableRecord, Circle, MText,
)
from Autodesk.AutoCAD.Colors import Color, ColorMethod
from Autodesk.AutoCAD.Geometry import Point3d, Vector3d
from Autodesk.Civil.ApplicationServices import CivilApplication

clr.AddReference("System.Windows.Forms")
from System.Windows.Forms import MessageBox

# Repo location of the standalone PyQGIS engine (01_Scripts/04_QGIS). Set it once per machine in
# %USERPROFILE%\.pynet\paths.json (not versioned):  {"qgis_dir": "C:\\Repos\\PyNetLibrary\\01_Scripts\\04_QGIS"}
_PATHS = Path.home() / ".pynet" / "paths.json"
QGIS_DIR = (Path(json.loads(_PATHS.read_text(encoding="utf-8"))["qgis_dir"]) if _PATHS.exists()
            else Path(r"C:\Repos\PyNetLibrary\01_Scripts\04_QGIS"))
CFG = json.loads((QGIS_DIR / "zona_activa.json").read_text(encoding="utf-8"))
OUT = QGIS_DIR / "output" / CFG["slug"]
DES_PATH = OUT / "desbroce_aerogeneradores.json"
if not DES_PATH.exists():
    raise Exception("Falta desbroce_aerogeneradores.json — ejecuta 07_DesbroceAerogeneradores.py")

data = json.loads(DES_PATH.read_text(encoding="utf-8"))
turbinas = data["turbinas"]
rad = float(data.get("radio_m", 50))
aep_total = data.get("aep_total_gwh", 0)
LAYER = "GIS_DESBROCE_AG"
OFF = 2.0


def col_of(score):   # combined priority score -> ACI colour (red/orange/green)
    return 1 if score >= 60 else 30 if score >= 35 else 3


doc = AcadApp.DocumentManager.MdiActiveDocument
db = doc.Database
civ = CivilApplication.ActiveDocument
sids = civ.GetSurfaceIds()
if sids.Count == 0:
    raise Exception("No hay superficie TIN en el dibujo (genera el terreno antes)")

lock = doc.LockDocument()
try:
    t = db.TransactionManager.StartTransaction()
    try:
        surface = t.GetObject(sids[0], OpenMode.ForRead)

        def zat(x, y):
            try:
                return surface.FindElevationAtXY(x, y) + OFF
            except Exception:
                return None

        lt = t.GetObject(db.LayerTableId, OpenMode.ForRead)
        if not lt.Has(LAYER):
            lt.UpgradeOpen()
            ltr = LayerTableRecord(); ltr.Name = LAYER
            ltr.Color = Color.FromColorIndex(ColorMethod.ByAci, 2)
            lt.Add(ltr); t.AddNewlyCreatedDBObject(ltr, True)
        bt = t.GetObject(db.BlockTableId, OpenMode.ForRead)
        ms = t.GetObject(bt[BlockTableRecord.ModelSpace], OpenMode.ForWrite)

        def add(ent, color):
            ent.Layer = LAYER
            ent.ColorIndex = color
            ms.AppendEntity(ent); t.AddNewlyCreatedDBObject(ent, True)

        erased = 0
        for oid in ms:
            e = t.GetObject(oid, OpenMode.ForRead)
            if hasattr(e, "Layer") and e.Layer == LAYER:
                e.UpgradeOpen(); e.Erase(); erased += 1

        drawn = 0
        for tb in turbinas:
            z = zat(tb["x"], tb["y"])
            if z is None:
                continue
            col = col_of(tb.get("score_prioridad", tb["pct_vegetacion"]))
            add(Circle(Point3d(tb["x"], tb["y"], z), Vector3d(0, 0, 1), rad), col)
            m = MText()
            m.Contents = "P%d %s\\P%d%% combustible | %.1f GWh" % (
                tb["prioridad"], tb["id"], tb["pct_vegetacion"], tb.get("aep_gwh", 0))
            m.Location = Point3d(tb["x"] + rad, tb["y"] + rad, z + 20)
            m.TextHeight = 22
            add(m, col)
            drawn += 1

        t.Commit()
    except:
        t.Abort()
        raise
finally:
    lock.Dispose()

top = sorted(turbinas, key=lambda d: d["prioridad"])[0]
print(f"Desbroce de aerogeneradores importado sobre {surface.Name} ({CFG['nombre']})")
print(f"Turbinas: {drawn} | radio {rad:.0f} m | entidades previas borradas: {erased}")
print(f"Generacion del parque: {aep_total} GWh/ano")
print(f"Prioridad 1: {top['id']} {top['pct_vegetacion']}% combustible, "
      f"{top.get('aep_gwh', 0)} GWh/ano (score {top.get('score_prioridad', 0)})")
MessageBox.Show(
    f"Desbroce de aerogeneradores ({CFG['nombre']})\n"
    f"Turbinas: {drawn} | radio: {rad:.0f} m | parque: {aep_total} GWh/ano\n"
    f"Prioridad 1: {top['id']} ({top['pct_vegetacion']}% combustible, "
    f"{top.get('aep_gwh', 0)} GWh)\n"
    f"Prioridad = vegetacion x generacion | capa: {LAYER}",
    "PyNET - Desbroce de aerogeneradores",
)
