# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 RAEN Digital Tools SL - PyNET Platform

# Button: import the fire-risk results for the active zone into Civil 3D.
# Source: 04_QGIS/output/<slug>/ (generated by 06_RiesgoIncendio_LineaAT.py):
#   - corredor_linea.geojson  AT line + corridor polygon
#   - prioridad_segmentos.json  per-segment risk ranking
#   - riesgo_incendio.json    risk heatmap cells
# Draws three layers, all DRAPED on the first TIN surface (FindElevationAtXY):
#   GIS_RI_CORREDOR (corridor), GIS_RI_LINEA (line by risk), GIS_RI_HEATMAP (hotspots).
# Re-running cleans those layers first.

import clr
import json
from pathlib import Path

clr.AddReference("AcMgd")
clr.AddReference("AcCoreMgd")
clr.AddReference("AcDbMgd")
clr.AddReference("AecBaseMgd")
clr.AddReference("AeccDbMgd")

from Autodesk.AutoCAD.ApplicationServices import Application as AcadApp
from Autodesk.AutoCAD.DatabaseServices import (
    OpenMode, BlockTableRecord, LayerTableRecord, Line, Circle, MText,
    Polyline3d, PolylineVertex3d,
)
from Autodesk.AutoCAD.Colors import Color, ColorMethod
from Autodesk.AutoCAD.Geometry import Point3d, Vector3d
from Autodesk.Civil.ApplicationServices import CivilApplication

clr.AddReference("System.Windows.Forms")
from System.Windows.Forms import MessageBox

# Repo location of the standalone PyQGIS engine (01_Scripts/04_QGIS). Set it once per machine in
# %USERPROFILE%\.pynet\paths.json (not versioned):  {"qgis_dir": "C:\\Repos\\PyNetLibrary\\01_Scripts\\04_QGIS"}
_PATHS = Path.home() / ".pynet" / "paths.json"
QGIS_DIR = (Path(json.loads(_PATHS.read_text(encoding="utf-8"))["qgis_dir"]) if _PATHS.exists()
            else Path(r"C:\Repos\PyNetLibrary\01_Scripts\04_QGIS"))
CFG = json.loads((QGIS_DIR / "zona_activa.json").read_text(encoding="utf-8"))
OUT = QGIS_DIR / "output" / CFG["slug"]

for f in ("corredor_linea.geojson", "prioridad_segmentos.json", "riesgo_incendio.json"):
    if not (OUT / f).exists():
        raise Exception(f"Falta {f} — ejecuta 06_RiesgoIncendio_LineaAT.py")

risk = json.loads((OUT / "riesgo_incendio.json").read_text(encoding="utf-8"))
segs = json.loads((OUT / "prioridad_segmentos.json").read_text(encoding="utf-8"))["segmentos"]
corr = json.loads((OUT / "corredor_linea.geojson").read_text(encoding="utf-8"))

LAYERS = {"GIS_RI_CORREDOR": 8, "GIS_RI_LINEA": 1, "GIS_RI_HEATMAP": 30}
HEATMAP_MAX = 1500
OFF = 2.0            # metres above the surface (avoid z-fighting)


def aci(r):          # risk -> colour (green/yellow/orange/red)
    return 1 if r >= 70 else 30 if r >= 55 else 2 if r >= 40 else 3


doc = AcadApp.DocumentManager.MdiActiveDocument
db = doc.Database
civ = CivilApplication.ActiveDocument
sids = civ.GetSurfaceIds()
if sids.Count == 0:
    raise Exception("No hay superficie TIN en el dibujo (genera el terreno antes)")

lock = doc.LockDocument()
try:
    t = db.TransactionManager.StartTransaction()
    try:
        surface = t.GetObject(sids[0], OpenMode.ForRead)

        def zat(x, y):                       # surface elevation, None if outside
            try:
                return surface.FindElevationAtXY(x, y) + OFF
            except Exception:
                return None

        lt = t.GetObject(db.LayerTableId, OpenMode.ForRead)
        for name, col in LAYERS.items():
            if not lt.Has(name):
                lt.UpgradeOpen()
                ltr = LayerTableRecord(); ltr.Name = name
                ltr.Color = Color.FromColorIndex(ColorMethod.ByAci, col)
                lt.Add(ltr); t.AddNewlyCreatedDBObject(ltr, True)
        bt = t.GetObject(db.BlockTableId, OpenMode.ForRead)
        ms = t.GetObject(bt[BlockTableRecord.ModelSpace], OpenMode.ForWrite)

        def add(ent, layer, color=None):
            ent.Layer = layer
            if color is not None:
                ent.ColorIndex = color
            ms.AppendEntity(ent); t.AddNewlyCreatedDBObject(ent, True)
            return ent

        def draped_pl(coords, layer, color):     # 3d polyline draped on the surface
            pl = add(Polyline3d(), layer, color)
            for x, y in coords:
                z = zat(x, y)
                if z is None:
                    continue
                v = PolylineVertex3d(Point3d(x, y, z))
                pl.AppendVertex(v); t.AddNewlyCreatedDBObject(v, True)
            return pl

        erased = 0
        for oid in ms:
            e = t.GetObject(oid, OpenMode.ForRead)
            if hasattr(e, "Layer") and e.Layer in LAYERS:
                e.UpgradeOpen(); e.Erase(); erased += 1

        # 1. corridor outline (draped)
        for f in corr["features"]:
            if f["geometry"]["type"] == "Polygon":
                draped_pl(f["geometry"]["coordinates"][0], "GIS_RI_CORREDOR", 8)

        # 2. AT line: one draped segment per tramo, coloured by risk
        for s in segs:
            z0, z1 = zat(s["x0"], s["y0"]), zat(s["x1"], s["y1"])
            if z0 is None or z1 is None:
                continue
            add(Line(Point3d(s["x0"], s["y0"], z0), Point3d(s["x1"], s["y1"], z1)),
                "GIS_RI_LINEA", aci(s["riesgo_medio"]))
        for s in sorted(segs, key=lambda d: d["prioridad"])[:5]:
            z = zat(s["x_centro"], s["y_centro"])
            if z is None:
                continue
            m = MText(); m.Contents = "P%d  R%d" % (s["prioridad"], s["riesgo_medio"])
            m.Location = Point3d(s["x_centro"], s["y_centro"] + 30, z + 20); m.TextHeight = 35
            add(m, "GIS_RI_LINEA", aci(s["riesgo_medio"]))

        # 3. risk heatmap: top cells as small draped circles
        cells = sorted(risk["cells"], key=lambda d: d["riesgo"], reverse=True)[:HEATMAP_MAX]
        half = risk["cell_size"] / 2.0
        drawn = 0
        for cl in cells:
            z = zat(cl["x"], cl["y"])
            if z is None:
                continue
            add(Circle(Point3d(cl["x"], cl["y"], z), Vector3d(0, 0, 1), half),
                "GIS_RI_HEATMAP", aci(cl["riesgo"]))
            drawn += 1

        t.Commit()
    except:
        t.Abort()
        raise
finally:
    lock.Dispose()

top = sorted(segs, key=lambda d: d["prioridad"])[0]
print(f"Riesgo de incendio importado sobre {surface.Name} ({CFG['nombre']})")
print(f"Tramos: {len(segs)} | heatmap: {drawn} | entidades previas borradas: {erased}")
print(f"Tramo critico P1: tramo {top['id']} riesgo medio {top['riesgo_medio']} "
      f"max {top['riesgo_max']} ({top['celdas_riesgo_alto']} celdas alto riesgo)")
MessageBox.Show(
    f"Linea AT - riesgo de incendio ({CFG['nombre']})\n"
    f"Tramos: {len(segs)} | puntos de riesgo: {drawn}\n"
    f"Tramo critico P1: tramo {top['id']} (riesgo medio {top['riesgo_medio']}, max {top['riesgo_max']})\n"
    f"Capas: GIS_RI_CORREDOR, GIS_RI_LINEA, GIS_RI_HEATMAP",
    "PyNET - Riesgo de incendio sobre la linea AT",
)
