# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 RAEN Digital Tools SL - PyNET Platform

# Button: insert the proposed wind turbines for the active zone.
# Zone comes from 04_QGIS/zona_activa.json; positions from output/<slug>/aerogeneradores.json
# (generated by 05_PosicionAerogeneradores.py). Inserts the configured block at each
# position (terrain elevation, configurable scale) on layer GIS_AEROGENERADORES with
# the AEROGENERADOR property set. Re-running cleans the layer first.
# If the block is missing from the drawing it is built here as 3D solids (real metres,
# tower base at z=0, rotor facing +X so the script's wind rotation orients it into the wind).

import clr
import json
import math
from pathlib import Path

clr.AddReference("AcMgd")
clr.AddReference("AcCoreMgd")
clr.AddReference("AcDbMgd")
clr.AddReference("AecBaseMgd")
clr.AddReference("AecPropDataMgd")

from Autodesk.AutoCAD.ApplicationServices import Application as AcadApp
from Autodesk.AutoCAD.DatabaseServices import (
    OpenMode, BlockTableRecord, BlockReference, LayerTableRecord, Solid3d,
)
from Autodesk.AutoCAD.Colors import Color, ColorMethod
from Autodesk.AutoCAD.Geometry import Point3d, Scale3d, Vector3d, Matrix3d
from Autodesk.Aec.PropertyData.DatabaseServices import (
    PropertySetDefinition, PropertyDefinition, PropertyDataServices,
)
from Autodesk.Aec.PropertyData import DataType

# Repo location of the standalone PyQGIS engine (01_Scripts/04_QGIS). Set it once per machine in
# %USERPROFILE%\.pynet\paths.json (not versioned):  {"qgis_dir": "C:\\Repos\\PyNetLibrary\\01_Scripts\\04_QGIS"}
_PATHS = Path.home() / ".pynet" / "paths.json"
QGIS_DIR = (Path(json.loads(_PATHS.read_text(encoding="utf-8"))["qgis_dir"]) if _PATHS.exists()
            else Path(r"C:\Repos\PyNetLibrary\01_Scripts\04_QGIS"))
CFG = json.loads((QGIS_DIR / "zona_activa.json").read_text(encoding="utf-8"))
AERO_PATH = QGIS_DIR / "output" / CFG["slug"] / "aerogeneradores.json"
LAYER_NAME = "GIS_AEROGENERADORES"
PSET_NAME = "AEROGENERADOR"
NOD_PSET_KEY = "AEC_PROPERTY_SET_DEFS"

# Turbine block geometry (metres, real scale) — 5 MW class machine
H_BUJE = 100.0          # hub height
R_TORRE_BASE = 2.6
R_TORRE_TOP = 1.5
L_NACELLE = 12.0
A_NACELLE = 4.0
L_PALA = 61.0           # rotor ~124 m
X_ROTOR = L_NACELLE * 0.5 + 0.5
Z_EJE = H_BUJE + A_NACELLE * 0.4


def crear_bloque_turbina(t, bt, nombre):
    """Build the turbine as 3D solids. Insertion point = tower base at z=0,
    rotor axis along +X so ref.Rotation aims it into the wind."""
    if bt.Has(nombre):
        btr = t.GetObject(bt[nombre], OpenMode.ForWrite)
        for oid in list(btr):
            t.GetObject(oid, OpenMode.ForWrite).Erase()
    else:
        bt.UpgradeOpen()
        btr = BlockTableRecord()
        btr.Name = nombre
        btr.Origin = Point3d(0, 0, 0)
        bt.Add(btr)
        t.AddNewlyCreatedDBObject(btr, True)

    solidos = []

    torre = Solid3d()
    torre.CreateFrustum(H_BUJE, R_TORRE_BASE, R_TORRE_BASE, R_TORRE_TOP)
    torre.TransformBy(Matrix3d.Displacement(Vector3d(0, 0, H_BUJE * 0.5)))
    solidos.append(torre)

    zapata = Solid3d()
    zapata.CreateFrustum(1.2, R_TORRE_BASE * 1.9, R_TORRE_BASE * 1.9, R_TORRE_BASE * 1.9)
    zapata.TransformBy(Matrix3d.Displacement(Vector3d(0, 0, 0.6)))
    solidos.append(zapata)

    gondola = Solid3d()
    gondola.CreateBox(L_NACELLE, A_NACELLE, A_NACELLE)
    gondola.TransformBy(Matrix3d.Displacement(Vector3d(-1.5, 0, Z_EJE)))
    solidos.append(gondola)

    buje = Solid3d()
    buje.CreateFrustum(3.0, 1.8, 1.8, 0.6)
    buje.TransformBy(Matrix3d.Displacement(Vector3d(0, 0, 1.5)))
    buje.TransformBy(Matrix3d.Rotation(math.radians(90), Vector3d.YAxis, Point3d(0, 0, 0)))
    buje.TransformBy(Matrix3d.Displacement(Vector3d(X_ROTOR - 0.5, 0, Z_EJE)))
    solidos.append(buje)

    for ang in (0.0, 120.0, 240.0):
        pala = Solid3d()
        pala.CreateFrustum(L_PALA, 2.4, 0.7, 0.35)
        pala.TransformBy(Matrix3d.Displacement(Vector3d(0, 0, L_PALA * 0.5 + 1.2)))
        pala.TransformBy(Matrix3d.Rotation(math.radians(ang), Vector3d.XAxis, Point3d(0, 0, 0)))
        pala.TransformBy(Matrix3d.Displacement(Vector3d(X_ROTOR, 0, Z_EJE)))
        solidos.append(pala)

    for s in solidos:
        s.Layer = "0"
        s.Color = Color.FromColorIndex(ColorMethod.ByBlock, 0)
        btr.AppendEntity(s)
        t.AddNewlyCreatedDBObject(s, True)

    print(f"Bloque '{nombre}' generado: {len(solidos)} solidos 3D "
          f"(buje {H_BUJE:.0f} m, rotor {L_PALA * 2 + 2.4:.0f} m)")

doc = AcadApp.DocumentManager.MdiActiveDocument
db = doc.Database

if not AERO_PATH.exists():
    raise Exception("Falta aerogeneradores.json — ejecuta 05_PosicionAerogeneradores.py")

data = json.loads(AERO_PATH.read_text(encoding="utf-8"))
turbinas = data["turbinas"]
block_name = data["bloque"]
escala = float(data.get("escala_bloque", 1.0))
# dir_viento: meteorological "from" degrees (N=0, CW). Convert to AutoCAD radians (CCW from E).
_dir = data.get("dir_viento")
rotation_rad = math.radians((90 - _dir) % 360) if _dir is not None else 0.0
print(f"Aerogeneradores propuestos: {len(turbinas)} ({data['zona']})")

clr.AddReference("System.Windows.Forms")
from System.Windows.Forms import MessageBox

lock = doc.LockDocument()
try:
    t = db.TransactionManager.StartTransaction()
    try:
        bt = t.GetObject(db.BlockTableId, OpenMode.ForRead)
        bloque_creado = not bt.Has(block_name)
        if bloque_creado:
            print(f"El bloque '{block_name}' no existe en el dibujo — se genera automaticamente")
            crear_bloque_turbina(t, bt, block_name)

        lt = t.GetObject(db.LayerTableId, OpenMode.ForRead)
        if not lt.Has(LAYER_NAME):
            lt.UpgradeOpen()
            ltr = LayerTableRecord()
            ltr.Name = LAYER_NAME
            ltr.Color = Color.FromColorIndex(ColorMethod.ByAci, 1)
            lt.Add(ltr)
            t.AddNewlyCreatedDBObject(ltr, True)

        nod = t.GetObject(db.NamedObjectsDictionaryId, OpenMode.ForRead)
        pset_dict = t.GetObject(nod[NOD_PSET_KEY], OpenMode.ForWrite)
        if not pset_dict.Contains(PSET_NAME):
            pset_def = PropertySetDefinition()
            pset_def.SetToStandard(db)
            pset_def.SubSetDatabaseDefaults(db)
            pset_def.Description = "Aerogenerador propuesto (analisis de aptitud)"
            pset_def.AppliesToAll = True
            defs = [("Id", DataType.Text, ""), ("Score", DataType.Real, 0.0),
                    ("VientoMs", DataType.Real, 0.0), ("CotaZ", DataType.Real, 0.0),
                    ("DistRedM", DataType.Real, 0.0), ("DirVientoDeg", DataType.Real, 0.0)]
            for name, dtype, default in defs:
                pd = PropertyDefinition()
                pd.SetToStandard(db)
                pd.SubSetDatabaseDefaults(db)
                pd.Name = name
                pd.DataType = dtype
                pd.DefaultData = default
                pset_def.Definitions.Add(pd)
            pset_dict.SetAt(PSET_NAME, pset_def)
            t.AddNewlyCreatedDBObject(pset_def, True)
            print(f"Property set creado: {PSET_NAME}")
        else:
            pset_def_rw = t.GetObject(pset_dict.GetAt(PSET_NAME), OpenMode.ForWrite)
            existing = [pset_def_rw.Definitions[i].Name for i in range(pset_def_rw.Definitions.Count)]
            if "DirVientoDeg" not in existing:
                pd = PropertyDefinition()
                pd.SetToStandard(db)
                pd.SubSetDatabaseDefaults(db)
                pd.Name = "DirVientoDeg"
                pd.DataType = DataType.Real
                pd.DefaultData = 0.0
                pset_def_rw.Definitions.Add(pd)
                print("Campo DirVientoDeg añadido al property set existente")
        pset_def = t.GetObject(pset_dict.GetAt(PSET_NAME), OpenMode.ForRead)

        ms = t.GetObject(bt[BlockTableRecord.ModelSpace], OpenMode.ForWrite)

        erased = 0
        for oid in ms:
            ent = t.GetObject(oid, OpenMode.ForRead)
            if hasattr(ent, "Layer") and ent.Layer == LAYER_NAME:
                ent.UpgradeOpen()
                ent.Erase()
                erased += 1
        if erased:
            print(f"Reimportacion: {erased} aerogeneradores anteriores eliminados")

        for tb in turbinas:
            ref = BlockReference(Point3d(tb["x"], tb["y"], tb["z"]), bt[block_name])
            ref.ScaleFactors = Scale3d(escala)
            ref.Rotation = rotation_rad
            ref.Layer = LAYER_NAME
            ms.AppendEntity(ref)
            t.AddNewlyCreatedDBObject(ref, True)

            PropertyDataServices.AddPropertySet(ref, pset_def.Id)
            pset = t.GetObject(PropertyDataServices.GetPropertySet(ref, pset_def.Id), OpenMode.ForWrite)
            pset.SetAt(pset.PropertyNameToId("Id"), tb["id"])
            pset.SetAt(pset.PropertyNameToId("Score"), float(tb["score"]))
            pset.SetAt(pset.PropertyNameToId("VientoMs"), float(tb["viento"]))
            pset.SetAt(pset.PropertyNameToId("CotaZ"), float(tb["z"]))
            pset.SetAt(pset.PropertyNameToId("DistRedM"), float(tb["dist_red"]))
            pset.SetAt(pset.PropertyNameToId("DirVientoDeg"), float(_dir or 0.0))
            print(f"  {tb['id']}: ({tb['x']:.0f}, {tb['y']:.0f}) cota {tb['z']:.0f} m, score {tb['score']}")

        t.Commit()
        print(f"Aerogeneradores insertados: {len(turbinas)} (bloque '{block_name}' x{escala})")
    except:
        t.Abort()
        raise
finally:
    lock.Dispose()

scores = [tb["score"] for tb in turbinas]
dir_txt = f"{_dir}° (Cierzo)" if _dir is not None else "no definida"
bloque_txt = f"'{block_name}' (generado en este dibujo)" if bloque_creado else f"'{block_name}'"
MessageBox.Show(
    f"Aerogeneradores: {len(turbinas)} (bloque {bloque_txt} x{escala})\n"
    f"Potencia estimada: {len(turbinas) * data['potencia_mw']:.0f} MW "
    f"({data['potencia_mw']} MW/maquina)\n"
    f"Score: {min(scores)} - {max(scores)} | separacion minima: {data['separacion_m']} m\n"
    f"Direccion viento: {dir_txt} | rotacion bloque: {math.degrees(rotation_rad):.0f}°\n"
    f"Capa: {LAYER_NAME} | property set: {PSET_NAME}",
    f"PyNET - Propuesta de parque eolico ({data['zona']})",
)
