# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 RAEN Digital Tools SL - PyNET Platform

# Button: insert the proposed wind turbines for the active zone.
# Zone comes from 04_QGIS/zona_activa.json; positions from output/<slug>/aerogeneradores.json
# (generated by 05_PosicionAerogeneradores.py). Inserts the configured block at each
# position (terrain elevation, configurable scale) on layer GIS_AEROGENERADORES with
# the AEROGENERADOR property set. Re-running cleans the layer first.

import clr
import json
from pathlib import Path

clr.AddReference("AcMgd")
clr.AddReference("AcCoreMgd")
clr.AddReference("AcDbMgd")
clr.AddReference("AecBaseMgd")
clr.AddReference("AecPropDataMgd")

from Autodesk.AutoCAD.ApplicationServices import Application as AcadApp
from Autodesk.AutoCAD.DatabaseServices import (
    OpenMode, BlockTableRecord, BlockReference, LayerTableRecord,
)
from Autodesk.AutoCAD.Colors import Color, ColorMethod
from Autodesk.AutoCAD.Geometry import Point3d, Scale3d
from Autodesk.Aec.PropertyData.DatabaseServices import (
    PropertySetDefinition, PropertyDefinition, PropertyDataServices,
)
from Autodesk.Aec.PropertyData import DataType

# Repo location of the standalone PyQGIS engine (01_Scripts/04_QGIS). Set it once per machine in
# %USERPROFILE%\.pynet\paths.json (not versioned):  {"qgis_dir": "C:\\Repos\\PyNetLibrary\\01_Scripts\\04_QGIS"}
_PATHS = Path.home() / ".pynet" / "paths.json"
QGIS_DIR = (Path(json.loads(_PATHS.read_text(encoding="utf-8"))["qgis_dir"]) if _PATHS.exists()
            else Path(r"C:\Repos\PyNetLibrary\01_Scripts\04_QGIS"))
CFG = json.loads((QGIS_DIR / "zona_activa.json").read_text(encoding="utf-8"))
AERO_PATH = QGIS_DIR / "output" / CFG["slug"] / "aerogeneradores.json"
LAYER_NAME = "GIS_AEROGENERADORES"
PSET_NAME = "AEROGENERADOR"
NOD_PSET_KEY = "AEC_PROPERTY_SET_DEFS"

doc = AcadApp.DocumentManager.MdiActiveDocument
db = doc.Database

if not AERO_PATH.exists():
    raise Exception("Falta aerogeneradores.json — ejecuta 05_PosicionAerogeneradores.py")

data = json.loads(AERO_PATH.read_text(encoding="utf-8"))
turbinas = data["turbinas"]
block_name = data["bloque"]
escala = float(data.get("escala_bloque", 1.0))
print(f"Aerogeneradores propuestos: {len(turbinas)} ({data['zona']})")

clr.AddReference("System.Windows.Forms")
from System.Windows.Forms import MessageBox

lock = doc.LockDocument()
try:
    t = db.TransactionManager.StartTransaction()
    try:
        bt = t.GetObject(db.BlockTableId, OpenMode.ForRead)
        if not bt.Has(block_name):
            t.Commit()
            MessageBox.Show(f"El bloque '{block_name}' no existe en el dibujo.",
                            "PyNET - Aerogeneradores")
            raise Exception(f"Bloque '{block_name}' no encontrado")

        lt = t.GetObject(db.LayerTableId, OpenMode.ForRead)
        if not lt.Has(LAYER_NAME):
            lt.UpgradeOpen()
            ltr = LayerTableRecord()
            ltr.Name = LAYER_NAME
            ltr.Color = Color.FromColorIndex(ColorMethod.ByAci, 1)
            lt.Add(ltr)
            t.AddNewlyCreatedDBObject(ltr, True)

        nod = t.GetObject(db.NamedObjectsDictionaryId, OpenMode.ForRead)
        pset_dict = t.GetObject(nod[NOD_PSET_KEY], OpenMode.ForWrite)
        if not pset_dict.Contains(PSET_NAME):
            pset_def = PropertySetDefinition()
            pset_def.SetToStandard(db)
            pset_def.SubSetDatabaseDefaults(db)
            pset_def.Description = "Aerogenerador propuesto (analisis de aptitud)"
            pset_def.AppliesToAll = True
            defs = [("Id", DataType.Text, ""), ("Score", DataType.Real, 0.0),
                    ("VientoMs", DataType.Real, 0.0), ("CotaZ", DataType.Real, 0.0),
                    ("DistRedM", DataType.Real, 0.0)]
            for name, dtype, default in defs:
                pd = PropertyDefinition()
                pd.SetToStandard(db)
                pd.SubSetDatabaseDefaults(db)
                pd.Name = name
                pd.DataType = dtype
                pd.DefaultData = default
                pset_def.Definitions.Add(pd)
            pset_dict.SetAt(PSET_NAME, pset_def)
            t.AddNewlyCreatedDBObject(pset_def, True)
            print(f"Property set creado: {PSET_NAME}")
        pset_def = t.GetObject(pset_dict.GetAt(PSET_NAME), OpenMode.ForRead)

        ms = t.GetObject(bt[BlockTableRecord.ModelSpace], OpenMode.ForWrite)

        erased = 0
        for oid in ms:
            ent = t.GetObject(oid, OpenMode.ForRead)
            if hasattr(ent, "Layer") and ent.Layer == LAYER_NAME:
                ent.UpgradeOpen()
                ent.Erase()
                erased += 1
        if erased:
            print(f"Reimportacion: {erased} aerogeneradores anteriores eliminados")

        for tb in turbinas:
            ref = BlockReference(Point3d(tb["x"], tb["y"], tb["z"]), bt[block_name])
            ref.ScaleFactors = Scale3d(escala)
            ref.Layer = LAYER_NAME
            ms.AppendEntity(ref)
            t.AddNewlyCreatedDBObject(ref, True)

            PropertyDataServices.AddPropertySet(ref, pset_def.Id)
            pset = t.GetObject(PropertyDataServices.GetPropertySet(ref, pset_def.Id), OpenMode.ForWrite)
            pset.SetAt(pset.PropertyNameToId("Id"), tb["id"])
            pset.SetAt(pset.PropertyNameToId("Score"), float(tb["score"]))
            pset.SetAt(pset.PropertyNameToId("VientoMs"), float(tb["viento"]))
            pset.SetAt(pset.PropertyNameToId("CotaZ"), float(tb["z"]))
            pset.SetAt(pset.PropertyNameToId("DistRedM"), float(tb["dist_red"]))
            print(f"  {tb['id']}: ({tb['x']:.0f}, {tb['y']:.0f}) cota {tb['z']:.0f} m, score {tb['score']}")

        t.Commit()
        print(f"Aerogeneradores insertados: {len(turbinas)} (bloque '{block_name}' x{escala})")
    except:
        t.Abort()
        raise
finally:
    lock.Dispose()

scores = [tb["score"] for tb in turbinas]
MessageBox.Show(
    f"Aerogeneradores: {len(turbinas)} (bloque '{block_name}' x{escala})\n"
    f"Potencia estimada: {len(turbinas) * data['potencia_mw']:.0f} MW "
    f"({data['potencia_mw']} MW/maquina)\n"
    f"Score: {min(scores)} - {max(scores)} | separacion minima: {data['separacion_m']} m\n"
    f"Capa: {LAYER_NAME} | property set: {PSET_NAME}",
    f"PyNET - Propuesta de parque eolico ({data['zona']})",
)
